"""add about_author column on users table

Revision ID: 112c147a7ea2
Revises: b11efe819fc5
Create Date: 2024-04-11 12:05:16.336146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112c147a7ea2'
down_revision = 'b11efe819fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
